"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.
Docs:
- https://docs.djangoproject.com/en/5.2/topics/settings/
- https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.conf import settings
import sys

try:
    import dj_database_url
except ImportError:
    print("Missing dependency: dj_database_url. Please install it with 'pip install dj-database-url'.", file=sys.stderr)
    raise

def csv_env(name: str, default: str) -> list[str]:
    """
    Lee una variable de entorno separada por comas y devuelve lista limpia.
    Ejemplo: "ALLOWED_HOSTS=.up.railway.app,.onrender.com,localhost"
    """
    return [s.strip() for s in os.getenv(name, default).split(",") if s.strip()]

# =========================
# Paths
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# Core / Security
# =========================
# Use env vars in production
# SECRET_KEY = os.getenv(
#     "SECRET_KEY",
#     "django-insecure-i+hu6sltx=%((ff1c_sw29tzs!5jc2o8$yho&r4=ot^h!rwc9d"  # dev fallback
# )

SECRET_KEY = os.getenv("SECRET_KEY", "dev-unsafe-key") 
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# Default hosts (adjust later to your domain)
ALLOWED_HOSTS = [
    ".onrender.com",
    ".up.railway.app",
    # "web-production-9a03.up.railway.app",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = (
    "https://*.onrender.com",
    "https://*.up.railway.app",
    "https://web-production-9a03.up.railway.app",

)

# If running behind a proxy (Render/Heroku/etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
# Harden cookies automatically in production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# =========================
# Apps
# =========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tracker',
    "crispy_forms",
    "crispy_bootstrap5",
    'widget_tweaks',
]

# =========================
# Middleware
# =========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =========================
# URLs / WSGI
# =========================
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# =========================
# Templates
# =========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "tracker.context_processors.navbar_categories",
                "tracker.context_processors.global_ui",
            ],
        },
    },
]

# =========================
# Database
# =========================
# Uses Postgres if DATABASE_URL is set; falls back to local SQLite
# 
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
X_FRAME_OPTIONS = 'SAMEORIGIN'
#DATABASES = {
#    'default': {
#       'ENGINE': 'mssql',
#        'NAME': 'Emerging Risk',
#        'USER': 'django',
#        'PASSWORD': 'django',
#        'HOST': '10.141.68.153',
#       'PORT': '1490',
#       'OPTIONS': {
#           'driver': 'ODBC Driver 17 for SQL Server',
#         },
#    }
#}

# if DATABASE_URL:
#     DATABASES = {
#         "default": dj_database_url.parse(
#             DATABASE_URL,
#             conn_max_age=600,
#             ssl_require=True, 
#         )
#     }
# else:
#     DATABASES = {
#         "default": {
#         'ENGINE': 'mssql',
#         'NAME': 'Emerging Risk',
#         'USER': 'django',
#         'PASSWORD': 'django',
#         'HOST': '10.20.68.38',
#         'PORT': '1490',
#         'OPTIONS': {
#         'driver': 'ODBC Driver 18 for SQL Server',
#         }
#         }
#     }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# =========================
# i18n / tz
# =========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =========================
# Static & Media
# =========================
# Static
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # your app's /static
STATIC_ROOT = BASE_DIR / "staticfiles"                 # required for collectstatic
# WhiteNoise for serving static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =========================
# Auth redirects
# =========================
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# =========================
# Crispy Forms
# =========================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# =========================
# Upload limits / Validations
# =========================
# 5MB in-memory request/file limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# General file cap (10MB) + allowed extensions
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
VALID_FILE_EXTENSIONS = ['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx']
FILE_UPLOAD_ALLOWED_EXTENSIONS = ['.pdf', '.doc', '.docx', '.xls', '.xlsx']

# =========================
# Defaults
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEBUG = True
ALLOWED_HOSTS = ['*']
# =========================
# Production (reference)
# =========================

# ALLOWED_HOSTS = ["<host_name>", "<host_ip>", "localhost", "127.0.0.1","JWPKSQLTOOLS01","JWPKSQLTOOLS01.corp.checkfree.com"]
#
 
 
# TEMPORAL - Para debug en producción
# DEBUG = True
# ALLOWED_HOSTS = ['*']  # Temporal
# Logging detallado

# LOGGING
##LOG_DIR = os.path.join(BASE_DIR, 'log')
#LOG_FILE = '/api.log'
#LOG_PATH = LOG_DIR + LOG_FILE

#if not os.path.exists(LOG_DIR):
##    os.mkdir(LOG_DIR)

#if not os.path.exists(LOG_PATH):
#    f = open(LOG_PATH, 'a').close() #create empty log file
#else:
#    f = open(LOG_PATH,"w").close() #clear log file

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             # 'filename': 'C:/Windows/Temp/emerging_risk_debug.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

LOGIN_URL = '/login/'


# STATIC_URL = '/static/'

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[3]

DEBUG = True

STATIC_ROOT = BASE_DIR / Path("static")
