# Generated by Django 5.2.7 on 2025-10-17 00:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTaxonomy',
            fields=[
                ('taxonomy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level1', models.CharField(max_length=250)),
                ('level2', models.CharField(max_length=350)),
                ('level3', models.CharField(max_length=350)),
            ],
            options={
                'db_table': '[EPAW].[vwIssueManagementRiskTaxonomy]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskTaxonomyLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTaxonomyLv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Political', 'Political'), ('Economic', 'Economic'), ('Social', 'Social'), ('Technological', 'Technological'), ('Legal', 'Legal'), ('Environmental', 'Environmental')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tracker_cat_name_102452_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('date_identified', models.DateField()),
                ('description', models.TextField()),
                ('impacted_lines', models.JSONField(default=list)),
                ('risk_taxonomy_lv1', models.JSONField(default=list)),
                ('risk_taxonomy_lv2', models.JSONField(default=list)),
                ('risk_taxonomy_lv3', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('HORIZON SCANNING', 'Horizon Scanning'), ('TRANSITION TO KNOWN RISK', 'Transition to known risk'), ('UNDER MONITORING', 'Under monitoring')], max_length=50)),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('control_in_place', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_identified'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('LINK', 'Link'), ('FILE', 'File'), ('MIXED', 'Mixed')], default='FILE', max_length=10)),
                ('source_date', models.DateField()),
                ('summary', models.TextField()),
                ('potential_impact', models.CharField(blank=True, choices=[('ESCALATING', 'Escalating'), ('DECREASING', 'Decreasing'), ('MAINTAINING', 'Maintaining')], max_length=20, null=True)),
                ('potential_impact_notes', models.TextField(blank=True, null=True)),
                ('link_or_file', models.URLField(blank=True, max_length=500)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='sources/%Y/%m/%d/')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='tracker.event')),
            ],
            options={
                'ordering': ['-source_date'],
            },
        ),
        migrations.CreateModel(
            name='SourceFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sources/%Y/%m/%d/')),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('replaced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_history', to='tracker.source')),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=40)),
                ('file', models.FileField(upload_to='temp_sources/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('MAIN', 'Main'), ('EXTRA', 'Extra')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('onset_timeline', models.CharField(choices=[('<1 year', '<1 year'), ('1-2 years', '1-2 years'), ('2+ years', '2+ years')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tracker.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.theme'),
        ),
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access Log',
                'verbose_name_plural': 'User Access Logs',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('object_key', models.TextField()),
                ('token', models.UUIDField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
                'indexes': [models.Index(fields=['-when'], name='tracker_dow_when_340c73_idx'), models.Index(fields=['token'], name='tracker_dow_token_db57e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['-source_date'], name='tracker_sou_source__47d951_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='tracker_sou_source__7addd3_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['-created_at'], name='tracker_the_created_f11c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['risk_rating'], name='tracker_the_risk_ra_509560_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date_identified'], name='tracker_eve_date_id_c7c751_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='tracker_eve_status_954236_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['risk_rating'], name='tracker_eve_risk_ra_2633a9_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['-login_time'], name='tracker_use_login_t_397665_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['user'], name='tracker_use_user_id_689cf7_idx'),
        ),
    ]
