# Generated by Django 5.2.4 on 2025-10-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
    ]
