# Generated by Django 5.2.4 on 2025-11-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
