# Generated by Django 5.2.4 on 2025-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_theme_risk_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='risk_rating',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
